# Generated by Django 6.0.7 on 2026-08-03 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure UUID used in the share URL. Never expose in list APIs for unauthorized users.', unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Allow location sharing for this person.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Admin user who created this person.', on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres.', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in m/s.', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees (0–360).', null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, help_text='Battery level 0.0–1.0.', null=True)),
                ('connection', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=120, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=120, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=60, null=True)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.person')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner'], name='tracking_pe_owner_i_a17ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['tracking_token'], name='tracking_pe_trackin_68707c_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['person', '-timestamp'], name='tracking_lo_person__e6e653_idx'),
        ),
    ]
